[alembic]
script_location = alembic

# Alembic будет брать DB_URL из окружения в `alembic/env.py`.
# Этот параметр здесь нужен только для валидности конфигурации.
sqlalchemy.url = postgresql+asyncpg://postgres:postgres@localhost:5432/goslog_navigator

